backend/socialite/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
    path("", views.index, name='index')
]

backend/socialite/socialite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/socialite/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    #path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

backend/socialite/users/models.py
from django.db import models

# Create your models here.

backend/socialite/homepage/views.py
import os
import tweepy
import requests
from django import forms
from django.conf import settings
from django.shortcuts import render, redirect
import facebook as fb
from django.contrib.auth.decorators import login_required

# Create your views here.


class NewPostForm(forms.Form):
    img = forms.ImageField()
    # task = forms.IntegerField(min_value=0, max_value=10)
    content = forms.CharField(label="content")


def handle_uploaded_file(f, fname):
    try:
        os.mkdir(str(settings.MEDIA_DIR))
    except:
        pass

    with open(str(settings.MEDIA_DIR) + '/' + fname, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def publish_to_tw(img, content):
    # OAuth 1.0a
    auth = tweepy.OAuthHandler(settings.TW_API_KEY, settings.TW_API_KEY_SECRET)
    auth.set_access_token(settings.TW_ACCESS_TOKEN,
                          settings.TW_ACCESS_TOKEN_SECRET)
    api = tweepy.API(auth)

    media = api.media_upload(str(settings.MEDIA_DIR) + '/' + img)

    print(media.media_id_string)

    return api.update_status(content, media_ids=[media.media_id_string])


def publish_to_fb(img, content):
    access_token = settings.FB_ACCESS_TOKEN
    graph_api = fb.GraphAPI(access_token=access_token)
    if img and content:
        r = graph_api.put_photo(
            open(str(settings.MEDIA_DIR) + '/' + img, "rb"), message=content)

    elif img:
        r = graph_api.put_photo(
            open(str(settings.MEDIA_DIR) + '/' + img, "rb"))
    else:
        r = graph_api.put_object("me", "feed", message=content)

    return r

@login_required
def index(request):
    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            content = form.cleaned_data["content"]
            img = str(form.cleaned_data["img"])

            # upload files to storage
            handle_uploaded_file(request.FILES['img'], img)
        else:
            return render(request, "homepage/index.html", context={
                "form": form
            })
        if content:
            print('Content: ', content)
            print(f"img: {img}")

            tw_response = publish_to_tw(img, content)
            fb_response = publish_to_fb(img, content)

            # print(f"tw_post_response: {tw_response}")
            # print(f"fb_post_response: {fb_response}")

            return redirect('index')

    return render(request, 'homepage/index.html', context={
        "form": NewPostForm()
    })

backend/socialite/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

# Create your views here.
# displays info about current signed in user


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    # ------------------------------- how to redirect to homepage ---------------------------------
    # return render(request, "users/user.html")
    return redirect('homepage:index')


def login_view(request):
    # if redirected from another page
    if 'next' in request.GET:
        return render(request, "users/login.html", context={
                "message": "Please login first"
        })

    # login authentication
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:  # authentication successful
            login(request, user)
            # ------------------------------- how to redirect to homepage ---------------------------------
            # return HttpResponseRedirect(reverse("users:index"))
            return redirect('homepage:index')

        else:
            return render(request, "users/login.html", context={
                "message": "invalid credentials"
            })
    return render(request, "users/login.html")


def logout_view(request):
    # django handles logout of user
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged Out"
    })

backend/socialite/homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Socialite</title>
    </head>
    <body>
        <h1>SOCIALITE</h1>
        <form method="post" action="{% url 'homepage:index' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <br>
            <button>Submit</button>
        </form>
        <a href="{% url 'users:logout' %}">Logout</a>
    </body>
</html>

backend/socialite/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Users</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

backend/socialite/users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block body %}
    {% if message %}
        <div>{{message}}</div>
    {% endif %}
    <form action="{% url 'users:login' %}" method= "post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
{% endblock %}

backend/socialite/users/templates/users/user.html
{% extends 'users/layout.html' %}

{% block body %}
    <!-- by default, have access to request -->
    <h1>Welcome, {{ request.user }}</h1>

    <ul>
        <li>Username: {{request.user.username}}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'users:logout' %}">Logout</a>
{% endblock %}